Repository campDevs/DiscordBot, pull requests merged in 2018-09, with the labels that each got.

#84 Add new command (8ball)
  src/commands/fun/8ball.js
  src/utils/8ball.json
Labels: review

#90 Remove deprecated method
  src/bot.js
Labels: bug, review, urgent

#92 Pin discord.js and commando versions
  package-lock.json
  package.json
Labels: review, urgent

#95 Update contributing.md
  CONTRIBUTING.md
  example_config.json
Labels: docs, review
